// clients/landing-react/src/register/Register.tsx
/*
 * Copyright 2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this
 * software and associated documentation files (the "Software"), to deal in the Software
 * without restriction, including without limitation the rights to use, copy, modify,
 * merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
 * permit persons to whom the Software is furnished to do so.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
 * PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
 * OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
 * SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */
import React from 'react';
import { Button, Col, Container, Form, InputGroup, Jumbotron, Row } from 'react-bootstrap';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { Formik, FormikProps } from 'formik';
import * as yup from 'yup';

const schema = yup.object({
  fullName: yup.string().required(),
  email: yup.string().required(),
  password: yup
    .string()
    .required()
    .matches(
      /((?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[\W]).{8,64})/,
      'Must be at least 8 characters, One Uppercase, One Lowercase, One Number and one special case Character'
    ),
  confirmPassword: yup.string().oneOf([yup.ref('password'), undefined], 'Passwords must match'),
  planId: yup.string().required(),
  terms: yup.bool().required(),
});

function Register() {
  return (
    <Container className="mt-3">
      <Row>
        <Col md={{ span: 8, offset: 2 }}>
          <Jumbotron className="text-center">
          <h1 >Hello, new SaaS Tenant!</h1>
          <p>
            Once submitted, this form will create a new tenant at the subdomain indicated.
          </p>
          </Jumbotron>
        </Col>
      </Row>
      <Row>
        <Col md={{ span: 6, offset: 3 }}>
          <Formik
            validationSchema={schema}
            onSubmit={console.log}
            initialValues={{
              fullName: '',
              email: '',
              password: '',
              confirmPassword: '',
              companyName: '',
              planId: '',
              terms: false,
            }}
          >
            {(formik: FormikProps<any>) => (
              <Form noValidate>
                <Form.Group controlId="validationFormik01">
                  <InputGroup>
                    <InputGroup.Prepend>
                      <InputGroup.Text>
                        <FontAwesomeIcon icon="user" />
                      </InputGroup.Text>
                    </InputGroup.Prepend>
                    <Form.Control
                      type="text"
                      name="fullName"
                      placeholder="Full Name"
                      value={formik.values.fullName}
                      onChange={formik.handleChange}
                      isValid={formik.touched.fullName && !formik.errors.fullName}
                    />
                  </InputGroup>
                  <Form.Control.Feedback>Looks good!</Form.Control.Feedback>
                </Form.Group>
                <Form.Group>
                  <InputGroup>
                    <InputGroup.Prepend>
                      <InputGroup.Text>
                        <FontAwesomeIcon icon="envelope" />
                      </InputGroup.Text>
                    </InputGroup.Prepend>
                    <Form.Control
                      type="text"
                      name="email"
                      placeholder="Email"
                      value={formik.values.email}
                      onChange={formik.handleChange}
                      isValid={formik.touched.email && !formik.errors.email}
                    />
                  </InputGroup>
                  <Form.Control.Feedback>Looks good!</Form.Control.Feedback>
                </Form.Group>
                <Form.Group>
                  <InputGroup>
                    <InputGroup.Prepend>
                      <InputGroup.Text>
                        <FontAwesomeIcon icon="asterisk" />
                      </InputGroup.Text>
                    </InputGroup.Prepend>
                    <Form.Control
                      type="password"
                      placeholder="Password"
                      aria-describedby="inputGroupPrepend"
                      name="password"
                      value={formik.values.password}
                      onChange={formik.handleChange}
                      isInvalid={!!formik.errors.password}
                    />
                    <Form.Control.Feedback type="invalid">
                      {formik.errors.password}
                    </Form.Control.Feedback>
                  </InputGroup>
                </Form.Group>
                <Form.Group>
                  <InputGroup>
                    <InputGroup.Prepend>
                      <InputGroup.Text>
                        <FontAwesomeIcon icon="asterisk" />
                      </InputGroup.Text>
                    </InputGroup.Prepend>
                    <Form.Control
                      type="password"
                      placeholder="Confirm Password"
                      aria-describedby="inputGroupPrepend"
                      name="confirmPassword"
                      value={formik.values.confirmPassword}
                      onChange={formik.handleChange}
                      isInvalid={!!formik.errors.confirmPassword}
                    />
                    <Form.Control.Feedback type="invalid">
                      {formik.errors.confirmPassword}
                    </Form.Control.Feedback>
                  </InputGroup>
                </Form.Group>
                <Form.Group>
                  <InputGroup>
                    <InputGroup.Prepend>
                      <InputGroup.Text>
                        <FontAwesomeIcon icon="building" />
                      </InputGroup.Text>
                    </InputGroup.Prepend>
                    <Form.Control
                      type="text"
                      placeholder="Company Name"
                      aria-describedby="inputGroupPrepend"
                      name="companyName"
                      value={formik.values.companyName}
                      onChange={formik.handleChange}
                      isInvalid={!!formik.errors.companyName}
                    />
                    <Form.Control.Feedback type="invalid">
                      {formik.errors.companyName}
                    </Form.Control.Feedback>
                  </InputGroup>
                </Form.Group>
                <Form.Group>
                  <Form.Check
                    required
                    name="terms"
                    label="Agree to terms and conditions"
                    onChange={formik.handleChange}
                    isInvalid={!!formik.errors.terms}
                    feedback={formik.errors.terms}
                    id="validationFormik0"
                  />
                </Form.Group>
                <Button type="submit">Submit form</Button>
              </Form>
            )}
          </Formik>
        </Col>
      </Row>
    </Container>
  );
}

export default Register;

// clients/Landing/src/app/register/register.component.ts
/*
 * Copyright 2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this
 * software and associated documentation files (the "Software"), to deal in the Software
 * without restriction, including without limitation the rights to use, copy, modify,
 * merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
 * permit persons to whom the Software is furnished to do so.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
 * PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
 * OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
 * SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */
import { HttpClient } from '@angular/common/http';
import { Component, OnInit } from '@angular/core';
import { FormGroup, FormBuilder, Validators } from '@angular/forms';
import { environment } from 'src/environments/environment';


@Component({
  selector: 'app-register',
  templateUrl: './register.component.html'
})
export class RegisterComponent implements OnInit {
  form: FormGroup;
  submitting = false;
  error = false;
  success = false;

  constructor(private fb: FormBuilder,
              private http: HttpClient) { }

  ngOnInit(): void {
    this.form = this.fb.group({
      name: [null, [Validators.required]],
      email: [null, [Validators.email, Validators.required]],
      password: [null, [Validators.required]],
      confirmPassword: [null, [Validators.required]],
      companyName: [null, [Validators.required]],
      plan: [null, [Validators.required]],
    }, {validator: this.pwdConfirming('password', 'confirmPassword')});
  }

  pwdConfirming(key: string, confirmationKey: string) {
    return (group: FormGroup) => {
        const input = group.controls[key];
        const confirmationInput = group.controls[confirmationKey];
        return confirmationInput.setErrors(
            input.value !== confirmationInput.value ? {notEquivalent: true} : null
        );
    };
  }

  onSubmit() {
    const API_URL = `${environment.apiUrl}/register`;
    const domain = environment.domain;
    const {
      confirmPassword,
      ...rest
    } = this.form.value;

    const user = {
      ...rest,
      customDomain: domain
    };

    this.submitting = true;
    this.http.post(API_URL, user)
    .subscribe(
      val => {
        this.submitting = false;
        this.success = true;
        this.error = false;
      },
      err => {
        this.submitting = false;
        this.success = false;
        this.error = true;
        console.log(err);
      }
    );
  }

  isFieldInvalid(field: string) {
    const formField = this.form.get(field);
    return formField.invalid && (formField.dirty || formField.touched);
  }

  displayFieldCss(field: string) {
    return {
      'is-invalid': this.isFieldInvalid(field),
    };
  }

  hasRequiredError(field: string) {
    return this.hasError(field, 'required');
  }

  hasError(field: string, error: any) {
    const formField = this.form.get(field);
    return !!formField.errors[error];
  }

  getTenantUrl() {
    const host: string[] = window.location.hostname.split('.');
    const companyName: string = this.form.value.companyName;
    const re = /[\W\s]+/g;
    const tenantId = companyName.replace(re, '').toLowerCase();
    const url = `https://${tenantId}.${host.length === 1 ? 'eks-ref-arch.com' : host.slice(1, 2)}`;
    return url;
  }
}

<alert type="danger" *ngIf="error" [dismissible]="true">
  <strong>Oh snap!</strong> There was an error provisioning your tenant.
</alert>
<alert type="success" *ngIf="success" [dismissible]="true">
  <strong>Success!</strong> Sucessfully provisioned your tenant.
</alert>
<div class="app-body">
  <main class="main d-flex align-items-center">
    <div class="container">
      <div class="row mt-3">
        <div class="col-md-6 mx-auto">
          <div class="card mx-4">
            <div class="card-body p-4">
              <form [formGroup]="form">
                <h1>Register</h1>
                <p class="text-muted">Create your account</p>
                <div class="form-group">
                  <div class="input-group">
                    <div class="input-group-prepend">
                      <span class="input-group-text"
                        ><i class="fa fa-user"></i
                      ></span>
                    </div>
                    <input
                      type="text"
                      id="fullname"
                      name="fullname"
                      class="form-control"
                      formControlName="name"
                      placeholder="Full Name"
                      [ngClass]="displayFieldCss('name')"
                      required
                    />
                  </div>
                  <div
                    *ngIf="isFieldInvalid('name')"
                    class="alert alert-danger"
                  >
                    <div *ngIf="hasRequiredError('name')">
                      Name is required.
                    </div>
                  </div>
                </div>
                <div class="form-group">
                  <div class="input-group">
                    <div class="input-group-prepend">
                      <span class="input-group-text"
                        ><i class="fa fa-envelope"></i
                      ></span>
                    </div>
                    <input
                      type="email"
                      id="email"
                      name="email"
                      class="form-control"
                      formControlName="email"
                      placeholder="Email"
                      [ngClass]="displayFieldCss('email')"
                      required
                    />
                  </div>
                  <div
                    *ngIf="isFieldInvalid('email')"
                    class="alert alert-danger"
                  >
                    <div *ngIf="hasRequiredError('email')">
                      Email is required.
                    </div>
                    <div *ngIf="hasError('email', 'email')">
                      Email is invalid.
                    </div>
                  </div>
                </div>
                <div class="form-group">
                  <div class="input-group">
                    <div class="input-group-prepend">
                      <span class="input-group-text"
                        ><i class="fa fa-asterisk"></i
                      ></span>
                    </div>
                    <input
                      type="password"
                      id="password"
                      name="password"
                      class="form-control"
                      formControlName="password"
                      placeholder="Password"
                      [ngClass]="displayFieldCss('password')"
                      required
                    />
                  </div>
                </div>
                <div class="form-group">
                  <div class="input-group">
                    <div class="input-group-prepend">
                      <span class="input-group-text"
                        ><i class="fa fa-asterisk"></i
                      ></span>
                    </div>
                    <input
                      type="password"
                      id="confirm-password"
                      name="confirm-password"
                      class="form-control"
                      formControlName="confirmPassword"
                      placeholder="Confirm Password"
                      [ngClass]="displayFieldCss('confirmPassword')"
                      required
                    />
                  </div>
                  <div
                    *ngIf="isFieldInvalid('confirmPassword')"
                    class="alert alert-danger"
                  >
                    <div *ngIf="hasRequiredError('confirmPassword')">
                      Confirm password is required.
                    </div>
                    <div *ngIf="hasError('confirmPassword', 'notEquivalent')">
                      Passwords don't match
                    </div>
                  </div>
                </div>
                <div class="form-group">
                  <div class="input-group">
                    <div class="input-group-prepend">
                      <span class="input-group-text"
                        ><i class="fa fa-building"></i
                      ></span>
                    </div>
                    <input
                      type="text"
                      id="company-name"
                      name="company-name"
                      class="form-control"
                      formControlName="companyName"
                      placeholder="Enter Company Name"
                      [ngClass]="displayFieldCss('companyName')"
                      required
                    />
                  </div>
                </div>
                <div class="form-group">
                  <label for="plan" class="text-muted">Please select your service plan</label>
                  <select
                    id="plan"
                    name="plan"
                    class="form-control"
                    formControlName="plan"
                    placeholder="Select Plan"
                    [ngClass]="displayFieldCss('plan')"
                    required
                  >
                    <option>Select one...</option>
                    <option value="basic">Basic</option>
                    <option value="standard">Standard</option>
                    <option value="premium">Premium</option>
                    <option value="platinum">Platinum</option>
                  </select>
                  <div
                    class="animated fadeIn text-center mt-3"
                    *ngIf="!!form.value['companyName']"
                  >
                    <span>Your application will be hosted at</span>
                    <div class="text-muted">
                      <a href="">{{ getTenantUrl() }}</a>
                    </div>
                  </div>
                </div>
              </form>
            </div>
            <div class="card-footer p-4">
              <div class="row">
                <div class="col-6">
                  <button
                    class="btn btn-block btn-primary"
                    (click)="onSubmit()"
                    type="button"
                  >
                    <span>Create</span>
                  </button>
                </div>
                <div class="col-6">
                  <button
                    class="btn btn-block btn-danger"
                    routerLink="/landing"
                    type="button"
                  >
                    <span>Cancel</span>
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </main>
</div>
